name: CI
run-name: Run Ansible Playbook
on: workflow_dispatch
jobs:
  run-playbooks:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i hosts.ini playbook.yml
          
